/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Inquiry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'preferredDate' : IDL.Text,
  'phone' : IDL.Text,
  'treatmentType' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'review' : IDL.Text,
  'name' : IDL.Text,
  'treatment' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'submitInquiry' : IDL.Func([Inquiry], [], []),
  'submitTestimonial' : IDL.Func([Testimonial], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Inquiry = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'preferredDate' : IDL.Text,
    'phone' : IDL.Text,
    'treatmentType' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'review' : IDL.Text,
    'name' : IDL.Text,
    'treatment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'submitInquiry' : IDL.Func([Inquiry], [], []),
    'submitTestimonial' : IDL.Func([Testimonial], [], []),
  });
};

export const init = ({ IDL }) => { return []; };